[postgres]
host = "127.0.0.1"
port = "5432"
user = "postgres"
password = "1234"
database = "postgres"

[neo4j]
host = "127.0.0.1"
port = "7687"
user = "neo4j"
password = "password"

[redis]
host = "127.0.0.1"
port = "6379"
db = "0"

[mongo]
host = "127.0.0.1"
port = 27017
db = "test"


[api]
host = "127.0.0.1"
port = 10000
token_minutes = 5